<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>spec.js.coffee</string>
		<string>spec.coffee</string>
	</array>
	<key>name</key>
	<string>Jasmine CoffeeScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(beforeEach|afterEach)\b(?![?!])</string>
			<key>name</key>
			<string>keyword.other.coffee</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(beforeEach|afterEach)\b(?![?!])</string>
			<key>name</key>
			<string>keyword.other.coffee</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\@\w+\b</string>
			<key>name</key>
			<string>entity.name.class.coffee</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#describe</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#it</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.coffee</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>describe</key>
		<dict>
			<key>begin</key>
			<string>^\s*(x?describe)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.coffee.behaviour</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.coffee.start-block</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.coffee.behaviour</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.coffee</string>
				</dict>
			</array>
		</dict>
		<key>it</key>
		<dict>
			<key>begin</key>
			<string>^\s*(it)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.coffee.example</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.coffee.start-block</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.coffee.example</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.coffee</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.coffee.jasmine</string>
	<key>uuid</key>
	<string>5c87cc44-13de-49bb-9c01-b8db446071d6</string>
</dict>
</plist>
